sudo: false
language: node_js
node_js:
- '6'
- '8'
- '10'
script: npm run travis
addons:
  sauce_connect:
    username: "okuryu"
  jwt:
    secure: "XuYKZ8+FtlcHWGXm7iCbqxvsTFUxgq968n3JpeWNirYK0G2w6EvPSlV97tipSGlekBGB//vpiQF2A9FcdFpNz0AIXyxh6qs/G3didEO1DRPaTQNOD8USSalof3J8AO4NSLxCPIWRVFYPqVR8hl0Eg2T9en3iAAfnME0XDHTZgpI="
